### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by PfiatDe** [ahhh/Cybersecurity-Tradecraft#1]
Hi,
great book so far, thanks for that.
Would it be possible to provide the links from the book somehow? It is a little bit annoying to retype all the links from the printed version :) 
If there are concerns regarding the knowledge, maybe a password would be a solution? Like the good old "4th word on page 135", etc.

**Comment by ahhh** [comment]
Great idea! You mean all of the links inline in the text right? I added references recently, but I can add these inline links as well.
The references just in-case: https://github.com/ahhh/Cybersecurity-Tradecraft/blob/main/References/references.md

**Comment by PfiatDe** [comment]
That's great. Thanks a lot!
